*** Settings ***
Library    Browser    timeout=30s

Resource    ./page_object/herokuapp/addremoveelements.resource
Resource    ./page_object/herokuapp/dropdown.resource
Resource    ./page_object/herokuapp/fileupload.resource
Resource    ./page_object/herokuapp/statuscodes.resource
Resource    ./page_object/herokuapp/horizontalslider.resource
Resource    ./page_object/herokuapp/checkbox.resource
Resource    ./page_object/herokuapp/tinymce.resource
Resource    ./page_object/herokuapp/filedownload.resource
Resource    ./page_object/herokuapp/entryad.resource
Resource    ./page_object/herokuapp/keypresses.resource
Resource    ./page_object/herokuapp/contextmenu.resource
Resource    ./page_object/herokuapp/login.resource
Resource    ./page_object/herokuapp/jqueryui.resource
